### ISSUE TITLE
提取的文字对应的翻译都是同一个

### ISSUE THREAD

**Issue by TheaWu7** [Styx11/react-intl-linter#13]
你好，我在进行项目的国际化的时候发现了你开发的 VSCode 插件，看了描述发现十分方便所以就在 VSCode 中下载使用了。
使用的过程中一开始是好的，如图：
<img width="670" alt="image" src="https://user-images.githubusercontent.com/91300914/163331427-d9d2f104-ceac-4d1b-af80-0639440997e9.png">
但是在为下一个字符串创建字典的时候出现了问题：
<img width="727" alt="image" src="https://user-images.githubusercontent.com/91300914/163331947-faf62d35-e3ac-4f9b-a34d-caa242f9358c.png">
翻译出的内容和上一个字符串一样，不匹配中文内容，又试了几次，都是同样的结果
<img width="680" alt="image" src="https://user-images.githubusercontent.com/91300914/163332398-b01f5b0c-301b-4ea9-8c3b-b4a1795221bf.png">
是我需要添加什么配置吗？
期待你的回复

**Comment by Styx11** [comment]
嗯我尽快看一下哈

**Comment by Styx11** [comment]
已修复，可以验证一下 @TheaWu7

**Comment by TheaWu7** [comment]
> 已修复，可以验证一下 @TheaWu7

cool，已经解决了
